### ISSUE TITLE
Bug: Opening Issues sometimes crashes the app

### ISSUE THREAD

**Issue by 0x5bfa** [0x5bfa/FluentHub#297]

**Comment by onein528** [comment]
@arihant2math Do you have any something contextual data such as log, screenshot?

**Comment by arihant2math** [comment]
**Stacktrace:**
```
   at y => new ReopenedEvent() {CreatedAt = y.CreatedAt, CreatedAtHumanized = y.CreatedAt.Humanize(null, null), Id = y.Id, StateReason = Convert(Convert(y.StateReason, IssueStateReason), Nullable`1), Actor = y.Actor.Select(actor => new Actor() {AvatarUrl = actor.AvatarUrl(Convert(Convert(100, Arg`1), Nullable`1)), Login = actor.Login}).SingleOrDefault()}(Closure , JToken )
   at Octokit.GraphQL.Core.Builders.Rewritten.Value.Switch[TResult](JToken source, IDictionary`2 selectors)
   at System.Linq.Enumerable.SelectIListIterator`2.MoveNext()
   at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at lambda_method(Closure , JObject )
   at Octokit.GraphQL.Core.Deserializers.ResponseDeserializer.Deserialize[TResult](Func`2 deserialize, JObject data)
   at Octokit.GraphQL.Core.Deserializers.ResponseDeserializer.Deserialize[TResult](Func`2 deserialize, String data)
   at Octokit.GraphQL.Core.SimpleQuery`1.Runner.RunPage(CancellationToken cancellationToken)
   at Octokit.GraphQL.ConnectionExtensions.Run[T](IConnection connection, ICompiledQuery`1 query, Dictionary`2 variables, CancellationToken cancellationToken)
   at FluentHub.Octokit.Queries.Repositories.IssueEventQueries.GetAllAsync(String owner, String name, Int32 number)
   at FluentHub.Uwp.ViewModels.Repositories.Issues.IssueViewModel.LoadRepositoryOneIssueAsync(String owner, String name)
   at FluentHub.Uwp.ViewModels.Repositories.Issues.IssueViewModel.LoadRepositoryIssuePageAsync()
   at Microsoft.Toolkit.Mvvm.ComponentModel.ObservableObject.<>c__DisplayClass20_0`1.<<SetPropertyAndNotifyOnCompletion>g__MonitorTask|0>d.MoveNext()
```

**Logs:**

[Log20220916.log](https://github.com/FluentHub/FluentHub/files/9585570/Log20220916.log)
