### ISSUE TITLE
Bug: Opening a pull request sometimes crashes the app

### ISSUE THREAD

**Issue by 0x5bfa** [0x5bfa/FluentHub#299]

**Comment by onein528** [comment]
@arihant2math Do you have any something contextual data such as log, screenshot?

**Comment by arihant2math** [comment]
Same as #297:

**Stacktrace:**
```
   at x => new Repository() {HomepageUrl = x.HomepageUrl, ForkingAllowed = x.ForkingAllowed, HasIssuesEnabled = x.HasIssuesEnabled, HasProjectsEnabled = x.HasProjectsEnabled, IsArchived = x.IsArchived, IsPrivate = x.IsPrivate, IsTemplate = x.IsTemplate, ViewerSubscription = Convert(Convert(x.ViewerSubscription, SubscriptionState), Nullable`1), Name = x.Name, Description = x.Description, StargazerCount = x.StargazerCount, ForkCount = x.ForkCount, IsFork = x.IsFork, IsInOrganization = x.IsInOrganization, ViewerHasStarred = x.ViewerHasStarred, UpdatedAt = x.UpdatedAt, LicenseInfo = x.LicenseInfo.Select(licenseInfo => new License() {Name = licenseInfo.Name}).SingleOrDefault(), DefaultBranchRef = x.DefaultBranchRef.Select(defaultbranchref => new Ref() {Name = defaultbranchref.Name}).SingleOrDefault(), Watchers = x.Watchers(null, null, null, null).Select(watchers => new UserConnection() {TotalCount = watchers.TotalCount}).Single(), Releases = x.Releases(null, null, null, null, null).Select(releases => new ReleaseConnection() {TotalCount = releases.TotalCount}).Single(), Issues = x.Issues(null, null, null, null, null, null, null, Convert(value(FluentHub.Octokit.Queries.Repositories.RepositoryQueries+<>c__DisplayClass1_0).issueState, Nullable`1)).Select(issues => new IssueConnection() {TotalCount = issues.TotalCount}).Single(), PullRequests = x.PullRequests(null, null, null, null, null, null, null, null, Convert(value(FluentHub.Octokit.Queries.Repositories.RepositoryQueries+<>c__DisplayClass1_0).pullRequestState, Nullable`1)).Select(issues => new PullRequestConnection() {TotalCount = issues.TotalCount}).Single(), Owner = x.Owner.Select(owner => new RepositoryOwner() {AvatarUrl = owner.AvatarUrl(Convert(Convert(100, Arg`1), Nullable`1)), Id = owner.Id, Login = owner.Login}).Single(), LatestRelease = x.Releases(null, null, Convert(Convert(1, Arg`1), Nullable`1), null, null).Nodes.Select(release => new Release() {DescriptionHTML = release.DescriptionHTML, IsDraft = release.IsDraft, IsLatest = release.IsLatest, IsPrerelease = release.IsPrerelease, Name = release.Name, PublishedAt = release.PublishedAt, Author = release.Author.Select(author => new User() {Login = author.Login, AvatarUrl = author.AvatarUrl(Convert(Convert(100, Arg`1), Nullable`1))}).Single()}).ToList().FirstOrDefault()}(Closure , JToken )
   at Octokit.GraphQL.Core.Builders.Rewritten.Value.Select[TResult](JToken source, Func`2 selector)
   at Octokit.GraphQL.Core.Deserializers.ResponseDeserializer.Deserialize[TResult](Func`2 deserialize, JObject data)
   at Octokit.GraphQL.Core.Deserializers.ResponseDeserializer.Deserialize[TResult](Func`2 deserialize, String data)
   at Octokit.GraphQL.Core.SimpleQuery`1.Runner.RunPage(CancellationToken cancellationToken)
   at Octokit.GraphQL.ConnectionExtensions.Run[T](IConnection connection, ICompiledQuery`1 query, Dictionary`2 variables, CancellationToken cancellationToken)
   at FluentHub.Octokit.Queries.Repositories.RepositoryQueries.GetDetailsAsync(String owner, String name)
   at FluentHub.Uwp.ViewModels.Repositories.PullRequests.ConversationViewModel.LoadRepositoryAsync(String owner, String name)
   at FluentHub.Uwp.ViewModels.Repositories.PullRequests.ConversationViewModel.LoadRepositoryPullRequestConversationPageAsync()
   at Microsoft.Toolkit.Mvvm.ComponentModel.ObservableObject.<>c__DisplayClass20_0`1.<<SetPropertyAndNotifyOnCompletion>g__MonitorTask|0>d.MoveNext()
```
**Logs:**
[Log20220916.log](https://github.com/FluentHub/FluentHub/files/9585593/Log20220916.log)

**Comment by xperiandri** [comment]
I have the same issue with all PRs I tried

**Comment by 0x5bfa** [comment]
Can you check if this issue is still present?
