### ISSUE TITLE
Bug: Custom date format breaks repos

### ISSUE THREAD

**Issue by BreadKat0707** [0x5bfa/FluentHub#449]
### Before you start

- [X] Have you updated FluentHub? You might be using an old version.
- [X] Have you checked if a similar issue has already been reported?

### What version of Windows is this issue present?

Windows 11 Dev

### What version/architecture of FluentHub are you on?

0.8.60.0 | X64 | RELEASE

### Description

When I try to open a repository, the page content flashes and then says Something went wrong string "time" was not recognized as a valid datetime
![图片](https://github.com/FluentHub/FluentHub/assets/61643570/b8cd264c-5ad5-4a5c-bd43-89df1888cb70)

### Expected behavior

Successfully open a repo page

### Stack Trace

<details><summary>Stack trace details</summary><div>

   at System.DateTimeOffset.Parse(String input)
   at FluentHub.Octokit.Queries.Repositories.TreeQueries.GetWithObjectNameAsync(String name, String owner, String refs, String path)
   at FluentHub.App.ViewModels.Repositories.Codes.DetailsLayoutViewModel.LoadRepositoryContentsAsync(String login, String name, String branch, String path)
   at FluentHub.App.ViewModels.Repositories.Codes.DetailsLayoutViewModel.LoadDetailsViewPageAsync()

</div></details>

### Assets

2023-12-31 22:18:50.777 +08:00 [ERR] LoadRepositoryContentsAsync
System.FormatException: String '2023.12.31.星期日 上午 08:28:59' was not recognized as a valid DateTime.
   at System.DateTimeOffset.Parse(String input)
   at FluentHub.Octokit.Queries.Repositories.TreeQueries.GetWithObjectNameAsync(String name, String owner, String refs, String path)
   at FluentHub.App.ViewModels.Repositories.Codes.DetailsLayoutViewModel.LoadRepositoryContentsAsync(String login, String name, String branch, String path)
   at FluentHub.App.ViewModels.Repositories.Codes.DetailsLayoutViewModel.LoadDetailsViewPageAsync()
2023-12-31 22:20:18.782 +08:00 [ERR] LoadRepositoryContentsAsync
System.FormatException: String '2023.03.29.星期三 上午 10:04:46' was not recognized as a valid DateTime.
   at System.DateTimeOffset.Parse(String input)
   at FluentHub.Octokit.Queries.Repositories.TreeQueries.GetWithObjectNameAsync(String name, String owner, String refs, String path)
   at FluentHub.App.ViewModels.Repositories.Codes.DetailsLayoutViewModel.LoadRepositoryContentsAsync(String login, String name, String branch, String path)
   at FluentHub.App.ViewModels.Repositories.Codes.DetailsLayoutViewModel.LoadDetailsViewPageAsync()

**Comment by 0x5bfa** [comment]
Thank you for the feedback. I guess Chinese version date time string is not recognized as a valid DataTime conversion target. I'm gonna investigate the cause and fix, but note that I don't have much time these days.

**Comment by Lamparter** [comment]
This issue is not related to Chinese DateTime format. Instead, it is about the date format being set in a format that is not default for the system, as explained by _`@just.a.hriday`_ [on Discord](https://discordapp.com/channels/935562861701390336/1286304489489436838/1287012687913681040):
> Oh I know the problem
I've gone and changed the windows short date format to a custom format
Because I wanted to see the day of the week in the taskbar
So ddd, d MMMM isn't a format microsoft expects 
And DateTime.Parse doesn't support it
But yeah, it's the same thing as in the issue you mentioned - the user's computer has a short date format that DateTime.Parse doesn't support.
I wonder what you could do about that though

**Comment by Lamparter** [comment]
I'm trying to reproduce this, give me a second...

**Comment by just-a-hriday** [comment]
It's also weird to me that the bug for me occured on the date of a seemingly random commit from the repository. Why not one of the other commits?

**Comment by just-a-hriday** [comment]
> Cannot reproduce after 4 attempts with different time format combinations, exactly matching the ones shown by @BreadKat0707 and _`@just.a.hriday`_ 😕

Looks like you've changed the time format - the issue is with the short date one.

**Comment by Lamparter** [comment]
> > Cannot reproduce after 4 attempts with different time format combinations, exactly matching the ones shown by @BreadKat0707 and _`@just.a.hriday`_ 😕
> 
> Looks like you've changed the time format - the issue is with the short date one.

How do you mean?
