### ISSUE TITLE
Bug: App fails to load Dashboard page

### ISSUE THREAD

**Issue by shrimqy** [0x5bfa/FluentHub#517]
### 🪟 What version of Windows is this issue present?

🪟 Windows 11 Beta

### 🔢 What version of FluentHub are you on?

0.9.0.0 | X64 | RELEASE

### 📄 Description

App fails to load dashboard with the following message:

_Object Reference not set to an instance of an object_

### 🪜 Steps To Reproduce

1. Launch Fluenthub normally.
2. Wait for the repostories to load on the side
3. Error

### 🤔 Expected behavior

Should show the dashboard normally.

### 📑 Stack Trace

```
   at FluentHub.Octokit.Wrappers.ActivityWrapper.Wrap(IReadOnlyList`1 response)
   at FluentHub.Octokit.Queries.Users.ActivityQueries.GetAllAsync(String login)
   at FluentHub.App.ViewModels.Viewers.DashBoardViewModel.LoadHomeContentsAsync()
   at FluentHub.App.ViewModels.Viewers.DashBoardViewModel.LoadUserHomePageAsync()
```

### 📸 Assets

[Log20240929.log](https://github.com/user-attachments/files/17179567/Log20240929.log)

**Comment by Lamparter** [comment]
@IviriusMain reported the exact same issue...

**Comment by 0x5bfa** [comment]
I can repro when I updated to the latest.
